# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5d3d20aab21c426abb2025497c84784603c07778d29464b4d91581297951dead331115583c057d872dbefb09140a80c08a4b5a3f68017efb1bb48bf3c608748

test:
  secret_key_base: b5ecebafda7977dad257ec2fa83b71906f3ded210b69e0598b6efdb639c09aaf03ffc6cc1ef9f271ae65644bfac57c2170c57bf8296462a8384da5e353f9e0e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
